<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCyPD4Et\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCyPD4Et/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCyPD4Et.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCyPD4Et\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCyPD4Et\App_KernelDevDebugContainer([
    'container.build_hash' => 'CyPD4Et',
    'container.build_id' => '7fbfe9a0',
    'container.build_time' => 1638519924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCyPD4Et');
