<?php

namespace ContainerLs98x4m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lmy25Q0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lmy25Q0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lmy25Q0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rpcode' => ['privates', 'App\\Repository\\CodeRepository', 'getCodeRepositoryService', true],
        ], [
            'em' => '?',
            'rpcode' => 'App\\Repository\\CodeRepository',
        ]);
    }
}
