<?php

namespace ContainerLs98x4m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersisters\ProduitDataPersister' shared autowired service.
     *
     * @return \App\DataPersisters\ProduitDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersisters/ProduitDataPersister.php';

        return $container->privates['App\\DataPersisters\\ProduitDataPersister'] = new \App\DataPersisters\ProduitDataPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\CatalogueRepository'] ?? $container->load('getCatalogueRepositoryService')));
    }
}
