<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLs98x4m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLs98x4m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLs98x4m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLs98x4m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLs98x4m\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ls98x4m',
    'container.build_id' => '875f1a81',
    'container.build_time' => 1638804296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLs98x4m');
